### ISSUE TITLE
[BUG] "[vite]: Rollup failed to resolve import" with vite-tsconfig-paths plugin

### ISSUE THREAD

**Issue by Giorno-Giovana** [aleclarson/vite-tsconfig-paths#135] opened 2024-01-27 00:25 UTC
### Source code
https://codesandbox.io/p/devbox/playwright-vite-representation-hxndcz

### Problem
```
[vite]: Rollup failed to resolve import "@/components/Counter" from "/workspaces/workspace/playwright/index.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
Error: [vite]: Rollup failed to resolve import "@/components/Counter" from "/workspaces/workspace/playwright/index.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

The reason is my `vite-tsconfig-paths` plugin. My App is working fine and TS imports too. But, for some reason, not in playwright.

### Steps to reproduce

Run `npm run test-ct`
___
This issue in playwright repo: https://github.com/microsoft/playwright/issues/29196

**Comment by Giorno-Giovana** [comment] 2024-01-29 13:49
If I write this code in playwright config, then everything will work. But this does not negate the fact that for some reason playwright does not want to work with vite-tsconfig-paths

```ts
alias: {
  '@': resolve(dirname('.'), './src'),
},
```

**Comment by JasonLandbridge** [comment] 2024-03-26 19:49
@Giorno-Giovana Did you manage to solve this? I got the same issue.

**Comment by k-teplyakov** [comment] 2024-03-27 19:48
me too

**Comment by JasonLandbridge** [comment] 2024-03-27 20:12
@k-teplyakov, In my case it was due to an update of Nuxt. See this issue for more info: https://github.com/nuxt/nuxt/issues/26512

**Comment by Razunter** [comment] 2024-04-27 12:14
I have the same issue with Bun on Windows

**Comment by is-jonreeves** [comment] 2024-09-17 21:50
I ran into the same issue on a Vanilla TS Backend project in a mono-repo (that has deps in the same npm workspace). I've been using `vitest` and this plugin with no issues, and then today added `vite` with the intention to use it to bundle the project (and deps excluding node) ready for production hosting (as the other monorepo packages will not be present in the deployment).

I used the same `plugins: [ tsconfigPaths() ]` as present in my `vitest.config.ts` file (that works for testing) but it was failed to build with the following error:
```
error during build:
[vite]: Rollup failed to resolve import "@/config" from "C:\Users\user\project\src\index.ts".    
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

After some tinkering I discovered that it only happens when using an explicit `rollupOptions.input/output` in my build configuration instead of vite's own build options. I'm not sure if this is a limitation of the plugin or a bug.

This doesn't work ❌:
```ts
import { defineConfig } from 'vite';
import { builtinModules } from 'module';

import aliases from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [
    aliases(),
  ],
  build: {
    minify: 'esbuild',
    sourcemap: true,
    rollupOptions: {
      external: [
        ...builtinModules,
      ],
      input: {
        server: 'src/index.ts',
      },
      output: {
        dir: 'dist/',
        format: 'cjs',
        entryFileNames: 'index.js',
      },
    },
  },
});
```
_Unless I also manually add `resolve.alias` entries myself._


But this does work ✅:
```ts
import { defineConfig } from 'vite';
import { builtinModules } from 'module';

import aliases from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [
    aliases(),
  ],
  build: {
    minify: 'esbuild',
    sourcemap: true,
    rollupOptions: {
      external: [
        ...builtinModules,
      ],
    },
    lib: {
      fileName: () => 'index.js',
      entry: 'src/index.ts',
      formats: ['cjs'],
    },
    outDir: 'dist/',
  },
});
```

Alternatively, omitting `rollupOptions` entirely and using `ssr: true` also worked. But for my usecase is not great, as it only bundled my local workspace deps meaning I still need to run `npm i --production` in production to get the public/npm packages... But that would fail because my mono-repo deps are not going to be found (as the mono repo is not present in this context) despite being bundled in code already.

For my purposes, the above "working" example that avoids `rollupOptions.input/output` is fine for now, but would be curious if this is a bug or limitation of the plugin.

**Comment by aleclarson** [comment] 2024-12-04 18:18
The reproduction appears to be bug free, so I'm closing this.

**Closed by aleclarson** 2024-12-04 18:18 UTC
