### ISSUE TITLE
Defining `include` while extending from a tsconfig that has `"files": []` or `"include": []` causes nothing to happen

### ISSUE THREAD

**Issue by jdharrisnz** [aleclarson/vite-tsconfig-paths#164] opened 2024-11-12 14:23 UTC
I'm using this plugin in a repo with TypeScript project references set up. The root tsconfig is the "solution" file that defines type checking and transformation rules, while each project directory extends from it. The root uses `"files": []`, however this seems to cause transformations not to happen.

Reproduction: https://github.com/jdharrisnz/8f0a73b9-9da1-40fd-8587-a0434aaf82a4

I'm using the tsc compiler with project references to build the project, but there's an element of my project for which I just want to run ad-hoc scripts via vite-node, and that's where this is choking.

**Comment by aleclarson** [comment] 2024-11-12 14:58
Add a minimal reproduction to https://github.com/aleclarson/vite-tsconfig-paths/tree/master/test/__fixtures__ (see other fixtures for guidance) and submit a PR. I will take a look then.

**Comment by jdharrisnz** [comment] 2024-11-13 22:54
Added the PR and deleted the above-linked repo

**Comment by aleclarson** [comment] 2024-11-19 20:45
I investigated a bit. This is a duplicate of #150, and it has nothing to do with empty `files` or `include` arrays. See [my comment](https://github.com/aleclarson/vite-tsconfig-paths/issues/150#issuecomment-2455284786) to understand what's happening. It's an upstream bug with `tsconfck`.

**Closed** 2024-11-19 20:45 UTC
Labels: duplicate
