### ISSUE TITLE
[vite:css] Failed to find '@/norm.css'

### ISSUE THREAD

**Issue by aladdin-add** [aleclarson/vite-tsconfig-paths#41] opened 2021-11-13 04:00 UTC
```bash
[vite:css] Failed to find '@/norm.css'
  in [
    /Users/weiran/repo/dian/vite-tsconfig-paths/demo/src
  ]
file: /Users/weiran/repo/dian/vite-tsconfig-paths/demo/src/styles.css
error during build:
Error: Failed to find '@/norm.css'
```

I've made a repro: #42

**Comment by aleclarson** [comment] 2022-02-06 21:22
This should be fixed by https://github.com/vitejs/vite/pull/3032, but someone needs to write tests for it before it can be merged :(

**Comment by bluwy** [comment] 2023-07-14 07:19
FWIW Astro has solved this with [this hack](https://github.com/withastro/astro/blob/db4095d3f5ef3de58183015cd3a1b311ac355c35/packages/astro/src/vite-plugin-config-alias/index.ts#L95-L138) and it has been working great so far.

**Comment by aleclarson** [comment] 2024-11-04 16:28
Duplicate of #30, so closing this.

**Closed by aleclarson** 2024-11-04 16:28 UTC
Labels: upstream bug
