### ISSUE TITLE
Couldnot correct load `ESM` module NodeNext with '.js' endfix.

### ISSUE THREAD

**Issue by tianyingchun** [aleclarson/vite-tsconfig-paths#70] opened 2022-10-23 02:09 UTC
```json
"compilerOptions": {
  "esModuleInterop": true,
    "module": "NodeNext",
    "target": "ESNext",
    "moduleResolution": "NodeNext",
    "baseUrl": "./src",
    "noImplicitAny": false,
    "allowJs": false,
    "noEmit": false,
    "incremental": true,
    "paths": {
      "@/test-utils": ["./test-utils/index.js"],
      "@/test-utils/*": ["./test-utils/*"],
```

import { runCliMock } from '@/test-utils/cli-run-mock.js';

it will throw Error: `[vite-node] Failed to load @/test-utils/cli-run-mock.js`

if use `import { runCliMock } from '@/test-utils/cli-run-mock` without `.js` endfix  it works

but in `type:module` nodeNext we must always using `.js`

**Comment by aleclarson** [comment] 2022-10-23 02:21
Duplicate of #54

**Closed by aleclarson** 2022-10-23 02:21 UTC
