### ISSUE TITLE
Broken in Vite 5

### ISSUE THREAD

**Issue by tervay** [aleclarson/vite-tsconfig-paths#129] opened 2023-12-10 05:00 UTC
https://stackblitz.com/edit/vitejs-vite-2pijh9?file=package.json

This stackblitz resembles a project structure I'm using that no longer works with Vite 5. In Vite 4, this project will (intentionally, in this Stackblitz case) fail due to a top-level await not being allowed in the configured environment (which is fine, expected, and desired in this case).

With Vite 5.0.2, this fails with the following stack trace:

```
❯ yarn build
yarn run v1.22.19
$ tsc && vite build
vite v5.0.2 building for production...
✓ 20 modules transformed.
[vite:worker] Cannot read properties of undefined (reading '/home/projects/vitejs-vite-2pijh9/src')
file: /home/projects/vitejs-vite-2pijh9/src/worker.ts?worker
error during build:
TypeError: Cannot read properties of undefined (reading '/home/projects/vitejs-vite-2pijh9/src')
    at Object.resolveId (file:///home/projects/vitejs-vite-2pijh9/node_modules/vite-tsconfig-paths/dist/index.mjs:175:45)
    at eval (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:18631:40)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:18531:28)
    at async resolveId (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:17200:26)
    at async ModuleLoader.resolveId (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:17614:15)
    at async Object.resolveId (file:///home/projects/vitejs-vite-2pijh9/node_modules/vite/dist/node/chunks/dep-ErEj4WmL.js:8150:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:18531:28)
    at async resolveId (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:17200:26)
    at async ModuleLoader.resolveId (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:17614:15)
    at async eval (file:///home/projects/vitejs-vite-2pijh9/node_modules/rollup/dist/es/shared/node-entry.js:17921:50)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not familiar enough with Vite to further debug this.

**Comment by wangpin34** [comment] 2023-12-16 15:33
yep, I also encounted with this issue on vite with version v5.0.10.

**Comment by divmgl** [comment] 2023-12-23 03:29
Unfortunately seems to be broken in Vite 5. 
<img width="508" alt="Screenshot 2023-12-22 at 10 29 30 PM" src="https://github.com/aleclarson/vite-tsconfig-paths/assets/5452298/e3dafd1e-3cde-497d-83cf-a58348294fb0">

**Comment by divmgl** [comment] 2023-12-23 03:30
Unfortunately can confirm that it seems to be broken in Vite 5.

TypeScript error:

```
No overload matches this call.
  The last overload gave the following error.
    Type 'Plugin<any>' is not assignable to type 'PluginOption'.
```

**Comment by dineug** [comment] 2023-12-23 04:02
vite-tsconfig-paths v3.6.0 downgrades will normal operation.

**Comment by aleclarson** [comment] 2023-12-24 17:27
I could not reproduce with the given StackBlitz, @tervay. I also tried reproducing manually,  but no luck. Please try clearing your node_modules, deleting your lockfile, and re-installing to see if that fixes it for you. Otherwise, please provide a proper reproduction, thanks.

**Comment by tervay** [comment] 2024-01-01 09:58
@aleclarson The stackblitz will fail when running `yarn build`. I'm not sure how to make it run that by default instead of `yarn run dev`, but `yarn build` will fail.

**Comment by davbrito** [comment] 2024-01-10 23:21
I'm having the same issue. It fails only when used as a **worker** plugin. Just like in the provided StackBlitz.



> I could not reproduce with the given StackBlitz, @tervay. I also tried reproducing manually, but no luck. Please try clearing your node_modules, deleting your lockfile, and re-installing to see if that fixes it for you. Otherwise, please provide a proper reproduction, thanks.

The error only shows when you run the build command:
![image](https://github.com/aleclarson/vite-tsconfig-paths/assets/39559632/55012195-8132-4f63-8661-3a6d58ce1aaa)

**Comment by davbrito** [comment] 2024-01-10 23:37
The error happens at this line: https://github.com/aleclarson/vite-tsconfig-paths/blob/dd3fc7e9ef353b0f53dc9720c00e722ad35f5104/src/index.ts#L164

My insight on this is that `resolveId` is being called before `configResolved`, or `configResolved` is not being called at all on the worker plugin. That way this line is not executed https://github.com/aleclarson/vite-tsconfig-paths/blob/dd3fc7e9ef353b0f53dc9720c00e722ad35f5104/src/index.ts#L125 and it ends up in the error since it's `undefined`.


----


I was able to workaround it by passing the same plugin object to both arrays, since it uses the same tsconfig for workers and main project. That way the `resolversByDir` gets prepopulated on the `configResolved` of the main plugin.

```js
const tspaths = tsconfigPaths()

export default defineConfig({
  plugins: [tspaths],
  worker { plugins: () => [tspaths] },
})
 ```

**Comment by aleclarson** [comment] 2024-01-13 18:46
This is a bug in Vite. I've opened [this PR](https://github.com/vitejs/vite/pull/15597) to fix it. Thanks for investigating, @davbrito. Neither of your suspicions were correct, but it helped save me some time. 👍

**Comment by aleclarson** [comment] 2024-01-15 18:15
Closing this. The Vite PR has been merged. Not sure what the release schedule is these days. If you have any other problems with Vite 5 and this plugin, open a new issue.

**Closed by aleclarson** 2024-01-15 18:15 UTC
Labels: waiting for response
