### ISSUE TITLE
Support `jsconfig.json` files

### ISSUE THREAD

**Issue by MichaelDeBoey** [aleclarson/vite-tsconfig-paths#51] opened 2022-05-03 12:06 UTC
`tsconfig-paths` v4.0.0 now supports `jsconfig.json` files. (see https://github.com/dividab/tsconfig-paths/pull/199)

https://github.com/dividab/tsconfig-paths/blob/master/CHANGELOG.md#400---2022-05-02

**Comment by aleclarson** [comment] 2022-05-22 03:38
This plugin doesn't use the `walkForTsconfig` function.

Also duplicate of #22

**Closed by aleclarson** 2022-05-22 03:38 UTC
