### ISSUE TITLE
ESM import `~/lib/util.js` doesn't work.

### ISSUE THREAD

**Issue by JuanM04** [aleclarson/vite-tsconfig-paths#59] opened 2022-06-27 21:51 UTC
With the introduction of ES Modules in TypeScript 4.7, TypeScript needs every import to have an extension. For example, if I have a file `util.ts`, I would need to import it as `./utils.js` (so that when transpiles to plain JavaScript, the import works as expected).

The addition of a `.js` to an aliased path by the plugin breaks the resolution. For example:

```ts
import "~/lib/util" // TS Error: module not found
import "../util.js" // ok
import "~/lib/util.js" // No TS Error, but Rollup throws "Rollup failed to resolve import"
```

**Comment by aleclarson** [comment] 2022-06-28 03:37
Can you fork the plugin, setup a repro in the example folder, and post link here? Thx

**Comment by JuanM04** [comment] 2022-06-28 18:21
https://github.com/JuanM04/vite-tsconfig-paths/tree/repro-59

The second line in `main.jsx` has been changed:

```diff
- import { Root } from '@/Root'
+ import { Root } from '@/Root.js'
```

With that setup, when you run `pnpm tsc --noEmit` that file doesn't throw an error (others do, but they don't matter in this example), but when you run `pnpm build` it throws. If you revert that change, TypeScript throws and Vite doesn't

**Comment by aleclarson** [comment] 2022-08-08 02:42
Duplicate of #54 I think?

**Closed by aleclarson** 2022-08-08 02:42 UTC
